### ISSUE TITLE
Dökümantasyondaki namespace yanlış galiba

### ISSUE THREAD

**Issue by ahmetersin** [EnterprisePHP/EPDisplayBundle#1]
Dökümantasyonda DisplayTrait bölümünde DisplayTrait'in namespace'i EP\DoctrineLockBundle\Traits\LockableTrait yazıyor fakat doğrusu EP\DisplayBundle\Entity\DisplayTrait; galiba

**Comment by delirehberi** [comment]
@ahmetersin06 fork / fix / pull-request :)
